export const API_DEFAULT_RETRY_COUNT = 3;
export const API_RETRYABLE_STATUS_CODES = [408, 429, 500, 502, 503, 504];
export const FEED_DEFAULT_PAGE_SIZE = 20;
export const PHASE1_MAX_FEED_RETRY_COUNT = 3;
export const PHASE1_FEED_DEFAULT_PAGE_SIZE = FEED_DEFAULT_PAGE_SIZE;
